###Get all items (GET)
GET http://localhost:5000/api/items

###Get items by category ID (GET)
GET http://localhost:5000/api/items/category/1

###Create a new item (POST)
POST http://localhost:5000/api/items
Content-Type: application/json

{
  "name": "iPhone 14",
  "description": "Latest Apple smartphone",
  "quantity": 10,
  "price": 999.99,
  "category_id": 5,
  "image_url": "https://example.com/iphone14.jpg"
}

###Get item by ID (GET)
GET http://localhost:5000/api/items/1

###Update item (PUT)
PUT http://localhost:5000/api/items/1
Content-Type: application/json

{
  "name": "iPhone 14 Pro",
  "description": "Upgraded Apple smartphone",
  "quantity": 8,
  "price": 1099.99,
  "category_id": 1,
  "image_url": "https://example.com/iphone14pro.jpg"
}

###Delete item (DELETE)
DELETE http://localhost:5000/api/items/1

###
POST http://localhost:5000/api/verify-admin/
Content-Type: application/json

{
  "password": "pratik123"
}